AUG:
  COLOR_AUG: 0.25
  RANDOM_CROP_PROB: 0.5
  SCALE_MAX: 2.0
  SCALE_MIN: 0.5
DATASET:
  FT: false
  TEST: LaF
  TRAIN: cityscapes_2class
  VAL: LaF
EXPERIMENT:
  EPOCHS: 200
  EVAL_INTERVAL: 1
  EVAL_METRIC: AnomalyEvaluator
  NAME: '20210311_212250_897984'
  OUT_DIR: ./training/experiments/
  RESUME_CHECKPOINT: null
  START_EPOCH: 0
  USE_BALANCED_WEIGHTS: false
INPUT:
  BASE_SIZE: 896
  BATCH_SIZE_TEST: 4
  BATCH_SIZE_TRAIN: 4
  CROP_SIZE: 896
  NORM_MEAN:
  - 0.485
  - 0.456
  - 0.406
  NORM_STD:
  - 0.229
  - 0.224
  - 0.225
LOSS:
  BATCH_AVG: true
  IGNORE_LABEL: 255
  SIZE_AVG: true
  TYPE: ReconstructionAnomalyLossFuseTrainAux
MODEL:
  BACKBONE: resnet
  FREEZE_BN: false
  NET: DeepLabReconFuseSimpleTrain
  OUT_STRIDE: 16
  RECONSTRUCTION:
    LATENT_DIM: 4
    SEGM_MODEL: jsr_code/checkpoints/checkpoint-segmentation.pth
    SEGM_MODEL_NCLASS: 19
    SKIP_CONN: false
    SKIP_CONN_DIM: 32
  SYNC_BN: false
OPTIMIZER:
  LR: 0.001
  LR_SCHEDULER: poly
  MOMENTUM: 0.9
  NESTEROV: false
  WEIGHT_DECAY: 0.0005
SYSTEM:
  GPU_IDS:
  - 0
  NUM_CPU: 1
  RNG_SEED: 42
  USE_GPU: true
